### ISSUE TITLE
Handling of variadic functions

### ISSUE THREAD

**Issue by hackel** [psalm/psalm-plugin-laravel#10]
Laravel makes use of the variadic function pattern quite a bit.  (func_get_args is used 110 times in the Framework code.)  Even a Laravel skeleton project starts out with this error:

    ERROR: TooManyArguments - app/Http/Controllers/Auth/VerificationController.php:34:44 - Too many arguments for method Illuminate\Routing\ControllerMiddlewareOptions::only - expecting 1 but saw 2
        $this->middleware('throttle:6,1')->only('verify', 'resend');

https://github.com/vimeo/psalm/issues/605 suggested plugin-based stubbing, which seems like it might be appropriate here.

**Comment by mr-feek** [comment]
I would vote that we close this issue, and prefer to open up individual issues for each  variadic function that has problems. It will be much easier to track progress that way!

**Comment by mr-feek** [comment]
I'm going to close this out, please open up any specific issues you may be having.

**Comment by ultrono** [comment]
I'm find a few of these myself i.e. `dispatchNow`. 

For the moment I'm just surpressing these via a DockBlock:

```
/** @psalm-suppress TooManyArguments */
Model::dispatchNow($user);

```
