### ISSUE TITLE
Support for Storage Facade

### ISSUE THREAD

**Issue by mr-feek** [psalm/psalm-plugin-laravel#101]
**Is your feature request related to a problem? Please describe.**

```php

$disk = Storage::disk('resources');
 
$path = 'definitions/features/';
foreach ($disk->files($path) as $file) {
    //
}

```

**Comment by lptn** [comment]
@mr-feek 
Do you mean `Illuminate\Support\Facades\Storage` or root namespace alias `\Storage`?
