### ISSUE TITLE
Allow more precise Eloquent relationship specification

### ISSUE THREAD

**Issue by Ignas2526** [psalm/psalm-plugin-laravel#115]
**Is your feature request related to a problem? Please describe.**
```
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    /**
     * @psalm-return \Illuminate\Database\Eloquent\Relations\HasMany<\App\Models\User>
     */
    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function something()
    {
        return $this->users()->first();
    }
}
```
The return type of `something()` type should be known and it should be `\App\Models\User|null`.

**Describe the solution you'd like**
The solution would be to support template in all of the relationship calls like in the above example.

**Comment by mr-feek** [comment]
I wasn't able to reproduce this in the test suite -- it should be working fine from what I can tell https://github.com/psalm/psalm-plugin-laravel/commit/fbf40a7f19f4e98fba6fefc60284d9fd8ecc12d9
