### ISSUE TITLE
Laravel 8.3+: optional() in RouteServiceProvider causes MixedPropertyFetch + MixedArgument errors

### ISSUE THREAD

**Issue by caugner** [psalm/psalm-plugin-laravel#119]
**Describe the bug**
As of Laravel 8.3.0 ([this commit](https://github.com/laravel/laravel/commit/bec982b0a3962c8a3e1f665e987360bb8c056298)), the `RouteServiceProvider` uses the helper `optional()`, which causes the following errors:

```
ERROR: MixedPropertyFetch - app/Providers/RouteServiceProvider.php:60:45 - Cannot fetch property on mixed var  (see https://psalm.dev/034)
            return Limit::perMinute(60)->by(optional($request->user())->id ?: $request->ip());
ERROR: MixedArgument - app/Providers/RouteServiceProvider.php:60:45 - Argument 1 of Illuminate\Cache\RateLimiting\Limit::by cannot be non-empty-mixed|null|string, expecting string (see https://psalm.dev/030)
            return Limit::perMinute(60)->by(optional($request->user())->id ?: $request->ip());
ERROR: PossiblyNullArgument - app/Providers/RouteServiceProvider.php:60:45 - Argument 1 of Illuminate\Cache\RateLimiting\Limit::by cannot be null, possibly null value provided (see https://psalm.dev/078)
            return Limit::perMinute(60)->by(optional($request->user())->id ?: $request->ip());
```

**Impacted Versions**
Affects Laravel 8.3.0 and later.

**Additional context**
I guess this could be fixed by adding stubs for both the `optional()` function and the `Optional` class:

1. `optional()` returns an `Optional` object if it's second `$callback` parameter is omitted.
2. `Optional::__get()` returns `null` unless the optional value is an object.

However, I'm not sure if it is possible to declare that `Optional::__get()` returns the value of the corresponding property (magic or not) on the value.

As for the `PossiblyNullArgument`, this would probably require to update the `Limit::by()` signature to accept `string|null`, since `Request::ip()` can return `null`.

PS: A workaround is to modify `RouteServiceProvider::configureRateLimiting()` as follows:
```
    /**
     * Configure the rate limiters for the application.
     *
     * @return void
     */
    protected function configureRateLimiting()
    {
        RateLimiter::for('api', function (Request $request) {
            /** @var User|null $user */
            $user = $request->user();

            /** @var \Illuminate\Support\Optional $optional */
            $optional = optional($user);

            /** @var string $key */
            $key = $optional->id ?: $request->ip();
            return Limit::perMinute(60)->by($key);
        });
    }
```

**Comment by caugner** [comment]
Feel free to use my attempt for the stubs, which didn't seem to work for me:

```php
<?php

/**
 * Provide access to optional objects.
 *
 * @template TValue of mixed
 * @template TResult of mixed
 * @template TCallbackOrNull of callable(TValue): TResult|null
 * @psalm-param  TValue $value
 * @psalm-param  TCallbackOrNull $callback
 * @psalm-return (TCallbackOrNull is null ? TResult : Illuminate\Support\Optional<TValue>)
 */
function optional($value = null, callable $callback = null)
{
}

namespace Illuminate\Support;

/**
 * @template TValue of mixed|null
 */
class Optional
{
    /**
     * @psalm-param TValue $value
     */
    public function __construct($value) {}

    /**
     * @psalm-param string $key
     * @psalm-return (TValue is object ? mixed : null)
     */
    public function __get($key) {}
}
```

**Comment by mr-feek** [comment]
Thanks for the report @caugner ! The automated tests are indeed catching this issue too, I'll try to take a look shortly

**Comment by mr-feek** [comment]
I took a stab at this, I'm also running into some issues. Documenting where I left off: https://github.com/psalm/psalm-plugin-laravel/pull/122

Feel free to give it a shot also

**Comment by mr-feek** [comment]
Just merged what I believe is a fix for `optional`
