### ISSUE TITLE
TooManyTemplateParams on morphOne

### ISSUE THREAD

**Issue by riasvdv** [psalm/psalm-plugin-laravel#127]
**Describe the bug**

[This PR](https://github.com/psalm/psalm-plugin-laravel/pull/81) added support for polymorphic relations, but morphOne seems to be missing.

**Impacted Versions**
vimeo/psalm 4.4.1 
psalm/plugin-laravel v1.4.2

**Comment by caugner** [comment]
Duplicate of #158, and fixed by #159.

@riasvdv Please try upgrading `psalm/plugin-laravel` to 1.4.8 or later.
