### ISSUE TITLE
Why `orchestra/testbench` isn't a require-dev?

### ISSUE THREAD

**Issue by stephandesouza** [psalm/psalm-plugin-laravel#130]
**Is your feature request related to a problem? Please describe.**
We're migrating `fzaninotto/faker` to `fakerphp/faker` but the `orchestra/testbench` makes it impossible to use it, failing on dependency resolution.

`psalm/plugin-laravel` is already a dev dependency on our project.

![image](https://user-images.githubusercontent.com/159077/110555912-3d278680-811c-11eb-8440-b079a9047d3a.png)

**Describe the solution you'd like**
Move `orchestra/testbench` to `require-dev`

**Describe alternatives you've considered**
I do not seed a reason to make it a normal require on package.

**Comment by stephandesouza** [comment]
Dang!

As I see, `ApplicationHelper` uses `Orchestra\Testbench\Concerns\CreatesApplication` so moving can cause errors when not requiring `orchestra/testbench` on projects.

**Comment by mr-feek** [comment]
Hey @stephandesouza !

`orchestra/testbench` is currently a dependency for support of _packages_. Developers  who create third party laravel packages need  to be able to run static analysis, but they don't necessarily have an _app_ to boot up. Testbench currently provides us one that we can easily use in those scenarios.

When doing your update, make sure to `--with-all-dependencies` to try updating the packages dependencies as well

**Comment by dionysiosarvanitis** [comment]
Alternatively, maybe `orchestra/testbench`  can be changed to `orchestral/testbench-core`. If this is all that it needs we can avoid loading unnecessary dependencies as it is pointed at https://github.com/orchestral/testbench/discussions/301#discussioncomment-474185
