### ISSUE TITLE
Plugin does not work with ide-helper version older than 2.9.1 in my case

### ISSUE THREAD

**Issue by salfum** [psalm/psalm-plugin-laravel#142]
**Describe the bug**
Psalm check failed, details in spoilers below depending on ide-helper version. The psalm and plugin-laravel versions do not change. In version 2.9.1, the psalm check was successful.
Apologies in advance for my english.
What needs to be done for the plugin to start working with ide-helper 2.10.0 ?
Adding a ': callable' calls 'Failed to load plugin Psalm\LaravelPlugin\Plugin at vendor/vimeo/psalm/src/Psalm/Config.php:1158'

**Impacted Versions**
barryvdh/laravel-ide-helper                    v2.10.0
laravel/framework                              v8.38.0
psalm/plugin-laravel                           v1.4.2
vimeo/psalm                                    4.7.0

**Additional context**
<details>
  <summary>Error log on ide-helper 2.9.2 - https://pastebin.com/juLPhhh6</summary>
 Scanning files...
PHP Fatal error:  Access level to Psalm\LaravelPlugin\FakeModelsCommand::getPropertiesFromTable() must be public (as in class Barryvdh\LaravelIdeHelper\Console\ModelsCommand) in /home/vagrant/code/back-slimmer/vendor/psalm/plugin-laravel/src/FakeModelsCommand.php on line 50

   Symfony\Component\ErrorHandler\Error\FatalError

  Access level to Psalm\LaravelPlugin\FakeModelsCommand::getPropertiesFromTable() must be public (as in class Barryvdh\LaravelIdeHelper\Console\ModelsCommand)

  at vendor/psalm/plugin-laravel/src/FakeModelsCommand.php:50
     46▕      * Load the properties from the database table.
     47▕      *
     48▕      * @param \Illuminate\Database\Eloquent\Model $model
     49▕      */
  ➜  50▕     protected function getPropertiesFromTable($model) : void
     51▕     {
     52▕         $table_name = $model->getTable();
     53▕
     54▕         if (!isset($this->schema->tables[$table_name])) {

   Whoops\Exception\ErrorException

  Access level to Psalm\LaravelPlugin\FakeModelsCommand::getPropertiesFromTable() must be public (as in class Barryvdh\LaravelIdeHelper\Console\ModelsCommand)

  at vendor/psalm/plugin-laravel/src/FakeModelsCommand.php:50
     46▕      * Load the properties from the database table.
     47▕      *
     48▕      * @param \Illuminate\Database\Eloquent\Model $model
     49▕      */
  ➜  50▕     protected function getPropertiesFromTable($model) : void
     51▕     {
     52▕         $table_name = $model->getTable();
     53▕
     54▕         if (!isset($this->schema->tables[$table_name])) {

      +1 vendor frames
  2   [internal]:0
      Whoops\Run::handleShutdown()
  
</details>

<details>
  <summary>Error log on ide-helper 2.10.0 - https://pastebin.com/VFuMXuGv</summary>
Scanning files...
PHP Fatal error:  Declaration of Psalm\LaravelPlugin\FakeMetaCommand::registerClassAutoloadExceptions() must be compatible with Barryvdh\LaravelIdeHelper\Console\MetaCommand::registerClassAutoloadExceptions(): callable in /home/vagrant/code/back-slimmer/vendor/psalm/plugin-laravel/src/FakeMetaCommand.php on line 11

   Symfony\Component\ErrorHandler\Error\FatalError

  Declaration of Psalm\LaravelPlugin\FakeMetaCommand::registerClassAutoloadExceptions() must be compatible with Barryvdh\LaravelIdeHelper\Console\MetaCommand::registerClassAutoloadExceptions(): callable

  at vendor/psalm/plugin-laravel/src/FakeMetaCommand.php:11
      7▕ {
      8▕     /**
      9▕      * @return void
     10▕      */
  ➜  11▕     protected function registerClassAutoloadExceptions()
     12▕     {
     13▕         // by default, the ide-helper throws exceptions when it cannot find a class. However it does not unregister that
     14▕         // autoloader when it is done, and we certainly do not want to throw exceptions when we are simply checking if
     15▕         // a certain class exists. We are instead changing this to be a noop.

   Whoops\Exception\ErrorException

  Declaration of Psalm\LaravelPlugin\FakeMetaCommand::registerClassAutoloadExceptions() must be compatible with Barryvdh\LaravelIdeHelper\Console\MetaCommand::registerClassAutoloadExceptions(): callable

  at vendor/psalm/plugin-laravel/src/FakeMetaCommand.php:11
      7▕ {
      8▕     /**
      9▕      * @return void
     10▕      */
  ➜  11▕     protected function registerClassAutoloadExceptions()
     12▕     {
     13▕         // by default, the ide-helper throws exceptions when it cannot find a class. However it does not unregister that
     14▕         // autoloader when it is done, and we certainly do not want to throw exceptions when we are simply checking if
     15▕         // a certain class exists. We are instead changing this to be a noop.

      +1 vendor frames
  2   [internal]:0
      Whoops\Run::handleShutdown()
</details>

Error log on ide-helper 2.10.0 with --debug-by-line option - https://pastebin.com/Z8M3v8w5

**Comment by salfum** [comment]
Sorry, I saw late in the release description that barrivdh broke semantic versioning. I close the issue.

**Comment by JC5** [comment]
How did you solve this?

**Comment by salfum** [comment]
> How did you solve this?

You need to downgrade version of ide-helper to 2.9.1
