### ISSUE TITLE
[8.x] Support new Model::factory() syntax

### ISSUE THREAD

**Issue by caugner** [psalm/psalm-plugin-laravel#155]
**Is your feature request related to a problem? Please describe.**
The new Laravel 8 factory syntax is not yet supported, so Psalm cannot determine the type of `User::factory()->make()` or `User::factory()->count(2)->make()` (which is equivalent to `User::factory(2)->make()`).

For a `App\Models\User` model, factories are now defined as follows:

* the `HasFactory` trait is used in the `User` class, which adds a static `factory()` method
* the corresponding `Database\Factories\UserFactory` is instantiated and returned
* if a numeric value is passed to `factory()`, this implicitly sets the `count()` accordingly

See also: https://laravel.com/docs/8.x/database-testing#defining-model-factories

**Describe the solution you'd like**
Add support for these factories.

**Describe alternatives you've considered**
(None.)

**Additional context**
As a workaround, I have added `<directory name="tests"/>` folder to the `<psalm><projectFiles><ignoreFiles>` section in the `psalm.xml` configuration.

**Comment by mr-feek** [comment]
Feel free to make a PR, I don't have any apps on laravel 8 yet

**Comment by lptn** [comment]
Laravel 9 (the only supported version but the plugin ATM) + Psalm support them out of the box
