### ISSUE TITLE
Composer test fails on Windows: "Failed to parse output: /usr/bin/env: ‘php\r’: No such file or directory"

### ISSUE THREAD

**Issue by caugner** [psalm/psalm-plugin-laravel#165]
**Is your feature request related to a problem? Please describe.**
I tried to `composer install` and run `composer test`, but this doesn't seem to be sufficient for running the tests (as it doesn't install Laravel). The README doesn't mention how to run these tests either.

**Describe the solution you'd like**
The README should describe how to run the tests locally (or more generally, how to contribute).

**Describe alternatives you've considered**
(None.)

**Additional context**
(None.)

**Comment by mr-feek** [comment]
Hey! I agree there could be some more documentation around contributing. There is a lot of overhead to be able to contribute to static analyzers. 

---

Composer install and composer test should be all that is required to run tests locally. Could you describe a little bit more about what doesn't work when you do that?

**Comment by caugner** [comment]
> Composer install and composer test should be all that is required to run tests locally.

Ah, you're right. This is related to #166:

```console
$ composer test
(...)

59) url:
 Test  tests/acceptance/UrlReturnType.feature:
Failed to parse output: /usr/bin/env: ‘php\r’: No such file or directory
Error:Syntax error

Scenario Steps:

 9. $I->canSeeNoErrors()
 8. $I->runPsalm()
 7. $I->haveTheFollowingCode("<?php\n  class Foo {\n    public function getUrlGenerator(): \Illuminate\Contracts\Routing\UrlGenerator {\n      return url();\n    }\n  }")
 6. $I->haveTheFollowingConfig("<?xml version="1.0"?>\n<psalm totallyTyped="true">\n  <projectFiles>\n    <directory name="."/>\n    <ignoreFiles> <directory name="../../vendor"/> </ignoreFiles>\n  </projectFiles>\n  <plugins>\n    <pluginClass class="Psalm\LaravelPlugin\Plugin"/>\n  </p...")
 5. // The global url helper will return the correct type depending on args


---------
60) url:
 Test  tests/acceptance/UrlReturnType.feature:
Failed to parse output: /usr/bin/env: ‘php\r’: No such file or directory
Error:Syntax error

Scenario Steps:

 9. $I->canSeeNoErrors()
 8. $I->runPsalm()
 7. $I->haveTheFollowingCode("<?php\n  class Foo {\n    public function getUrl(): string {\n      return url('example.com');\n    }\n  }")
 6. $I->haveTheFollowingConfig("<?xml version="1.0"?>\n<psalm totallyTyped="true">\n  <projectFiles>\n    <directory name="."/>\n    <ignoreFiles> <directory name="../../vendor"/> </ignoreFiles>\n  </projectFiles>\n  <plugins>\n    <pluginClass class="Psalm\LaravelPlugin\Plugin"/>\n  </p...")
 5. // The global url helper will return the correct type depending on args


FAILURES!
Tests: 60, Assertions: 60, Failures: 60.
Script @php vendor/bin/codecept run --skip-group skip handling the test event returned with error code 1
```

**Comment by caugner** [comment]
**Results**:

1. Don't set `git config --global core.autocrlf true` inside WSL2, but set `git config --global core.autocrlf input` instead. 
2. Don't bother running Psalm directly on Windows (see https://github.com/psalm/psalm-plugin-laravel/pull/166#issuecomment-874212732).
