### ISSUE TITLE
Rereview #154

### ISSUE THREAD

**Issue by tm1000** [psalm/psalm-plugin-laravel#187]
In #154 it was stated that newer versions of ide helper (greater than 2.9.2) would not be supported  because they dropped support for laravel 6 and 7. 21 hours ago #185 was merged which removes support for laravel 7 in this package. So isn't that point moot now. This package itself only supports laravel 8 so shouldn't it be made compatible with the newest ide helper if that was the reason holding it back

**Comment by mr-feek** [comment]
This package supports Laravel 6, the LTS version

**Comment by tm1000** [comment]
Ah right

**Comment by jpresutti** [comment]
Laravel 6 is EOL as of 11 days ago. @mr-feek I would really like to use this on a project that is using a newer version of the ide helper.

**Comment by mr-feek** [comment]
@jpresutti laravel 6 is the LTS version, which has bug fixes until September 3rd, 2022

**Comment by jpresutti** [comment]
That is incorrect. Bug fix support ended Sept 3rd. It is security fixes only. 
![Screenshot_20210916-090642_Samsung Internet](https://user-images.githubusercontent.com/6835477/133617624-81d04d93-13f8-43e3-b3bc-275e678bff89.jpg)
Read the docs.

https://laravel.com/docs/6.x/releases

By not having a version line that supports the newer version of ide helper you are locking out a LOT of projects. If you insist on supporting a version that's reached EOL then perhaps you should do a version jump for also supporting the newer version.

**Comment by tm1000** [comment]
Agree with this ^

Also he's not the only one to request it working with newer ide helper

**Comment by mr-feek** [comment]
@tm1000 @jpresutti like I've said a bunch, if you can resolve this issue while still supporting laravel 6 then I will gladly merge a PR

**Comment by jpresutti** [comment]
@mr-feek did you actually read the part where you are liliterally wrong about Laravel 6 still getting bug fixes?

**Comment by mr-feek** [comment]
@jpresutti would you like me to apologize for a typo? I meant security fixes. Are you actually wasting your time being rude to someone who spent hundreds of hours making this open source package, instead of taking the time to propose a fix?

**Comment by mr-feek** [comment]
@jpresutti fork it, you're on your own for being a jerk to open source maintainers.

**Comment by jpresutti** [comment]
It... it was a serious question. That being said, I'm actually wrong. They pushed it back till January even tho 9 is LTS so I'll see myself out.

**Comment by mr-feek** [comment]
Or you know, spend 20 minutes making a PR to support both versions. You know, read the docs @jpresutti https://www.php.net/

**Comment by jpresutti** [comment]
The whole point of things like Laravel 6,7,8 etc is so there can be multiple supported versions. Your "there can be only one version line" approach is costing users the ability to use the library. The same for there being PHP 7.3, 7.4 and 8 all active at the same time. Again, I was being serious and not trying to be a jerk, and I also said I was wrong on the date because they updated one doc and not another, so you can stop with the snark at any time. It's not a good optic

**Comment by mr-feek** [comment]
PRs welcome

**Comment by tm1000** [comment]
> Or you know, spend 20 minutes making a PR to support both versions.

I don't think it's possible to do this because the issue is they changed method properties in ide helper. This project would have to have two active versions.

**Comment by mr-feek** [comment]
@tm1000 a simple version_compare and substituting this package's bindings should suffice

**Comment by mr-feek** [comment]
I started sketching it out, feel free to finish it https://github.com/psalm/psalm-plugin-laravel/tree/support-newer-ide-helper
