### ISSUE TITLE
Support current laravel-ide-helper

### ISSUE THREAD

**Issue by tminich** [psalm/psalm-plugin-laravel#204]
**Is your feature request related to a problem? Please describe.**
We've just updated our cuurent project to Laravel 8 and PHP 8, two of the main reasons were to be able to use Psalm efficiently and update laravel-ide-helper to support hooks (a feature introduced in 2.9.2) which will be important to remove certain workarounds in our internal tooling. This plugin would lock us to a version that does not suppport this.

**Describe the solution you'd like**
Support the current version, as of this writing 2.10.0

**Describe alternatives you've considered**
There's not really an alternative as it's either use psalm fully or laravel-ide-helper hooks :)

**Comment by mr-feek** [comment]
Feel free to finish the pr i sketched out https://github.com/psalm/psalm-plugin-laravel/issues/187#issuecomment-921151991

I don't personally have the need for this, so it hasn't been a priority of mine.

**Comment by yaegassy** [comment]
Hi, @tminich 

There seems to be a package that supports the latest laravel-ide-helper by fork.

- <https://packagist.org/packages/brokeyourbike/plugin-laravel>

It seems to be listed in the plugins page of psalm. <https://psalm.dev/plugins>

**Comment by tminich** [comment]
> Hi, @tminich
> 
> There seems to be a package that supports the latest laravel-ide-helper by fork.
> 
>     * https://packagist.org/packages/brokeyourbike/plugin-laravel
> 
> 
> It seems to be listed in the plugins page of psalm. https://psalm.dev/plugins

Thanks, I'll take a look

**Comment by maximal** [comment]
Thank you, @yaegassy! `brokeyourbike/plugin-laravel` works fine.

**Comment by mr-feek** [comment]
Support for newer IDE helper versions has just been merged to master. Please help test! I will cut a new release next week, giving ample time for testing with newer IDE helper versions.

https://github.com/psalm/psalm-plugin-laravel/pull/226
