### ISSUE TITLE
Add stubs for Collection (template/generics)

### ISSUE THREAD

**Issue by vladyslavstartsev** [psalm/psalm-plugin-laravel#23]
Since Laravel collections are quite popular and I'm not sure that it will be typed (I mean template annotations in Laravel code; see this https://github.com/laravel/framework/pull/31486#issuecomment-586609823), I would like to suggest adding stubs for Collection.

**Comment by muglug** [comment]
Could you?

**Comment by vladyslavstartsev** [comment]
probably yes, but not promising

**Comment by muglug** [comment]
Also amused by @voku’s ill-fated attempt to impose any sort of external constraints on the code in Laravel core.

`laravel/framework` is an untamed horse galloping across the Great Plains, ya know... it’s this magnificent beast that knows no bondage, and you want to put a saddle on it? That’s just not right, man. Real PHP artisans would understand.

**Comment by mr-feek** [comment]
@vladyslavstartsev @muglug I took a shot at this #32
