### ISSUE TITLE
Collection stub. Missing reduce definition

### ISSUE THREAD

**Issue by Legion112** [psalm/psalm-plugin-laravel#237]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Legion112** [comment]
Should be something like that
```
    /**
     * Reduce the collection to a single value.
     * @template TReturn
     * @template TInit
     * @param  callable(TInit, TValue):TReturn  $callback
     * @param  TInit  $initial
     * @return TReturn
     */
    public function reduce(callable $callback, $initial = null);
```

**Comment by lptn** [comment]
Hey @Legion112 
Which Laravel version do you use? In modern Laravel 9 collections already have right syntax:
```php

    /**
     * Reduce the collection to a single value.
     *
     * @template TReduceInitial
     * @template TReduceReturnType
     *
     * @param  callable(TReduceInitial|TReduceReturnType, TValue, TKey): TReduceReturnType  $callback
     * @param  TReduceInitial  $initial
     * @return TReduceReturnType
     */
    public function reduce(callable $callback, $initial = null);

```

**Comment by Legion112** [comment]
Laravel 6 or something

**Comment by lptn** [comment]
@Legion112 

Oh, this is ancient Laravel version. We don't support it anymore, but you are free to create a PR for it. Everything you need:
 - branch off from latest 1.x tag (this is 1.6.2 ATM)
 - open https://github.com/psalm/psalm-plugin-laravel/blob/v1.6.2/stubs/Collection.stubphp and update it by annotations from https://github.com/laravel/framework/blob/9.x/src/Illuminate/Collections/Enumerable.php

We will appropriate any help on this repository

**Comment by lptn** [comment]
closing as outdated (I highly recommend to use a new version 2.5 of the plugin BTW)
