### ISSUE TITLE
Can't install v1.x on Laravel 7.x

### ISSUE THREAD

**Issue by riaanduplessis** [psalm/psalm-plugin-laravel#238]
**Describe the bug**
The dependencies of version 1.x require either version 6 or 8 of various illuminate packages.

Since those illuminate packages are on version 7 when Laravel is also on 7, composer cannot install this package.

**Impacted Versions**

v1.x

**Additional context**

https://github.com/psalm/psalm-plugin-laravel/blob/8c46a820d4de59ae601a9fcf5534df6bb03e619a/composer.json#L16-L24

**Comment by mr-feek** [comment]
support for Laravel 7 was dropped in 1.5.0 as Laravel 7 reached end of life (https://github.com/psalm/psalm-plugin-laravel/pull/185)

Use v1.4.9 of this package.
