### ISSUE TITLE
Collection isNotNull isNull methods

### ISSUE THREAD

**Issue by Legion112** [psalm/psalm-plugin-laravel#239]
Should be something like this
```php
    /**
     * @psalm-assert-if-true TValue !empty($this->items)
     * @psalm-assert-if-true TValue $this->first()
     * @psalm-mutation-free
     */
    public function isNotEmpty():bool {}
```

Also this option have to be set to support this check https://psalm.dev/docs/running_psalm/configuration/#memoizemethodcallresults
https://psalm.dev/docs/annotating_code/adding_assertions/    

Example from documentation:
<img width="798" alt="image" src="https://user-images.githubusercontent.com/20613430/195586392-b42b494a-6634-4edb-9811-920385f69afe.png">

**Comment by lptn** [comment]
`$this->first()` has parameters, so it's not correct to use `@psalm-assert-if-true TValue $this->first()`. I've added some very basic code here: https://github.com/psalm/psalm-plugin-laravel/pull/313/files 

Feel free to improve this PR and suggest more changes
