### ISSUE TITLE
 Class 'Illuminate\Support\Facades\Date' not found

### ISSUE THREAD

**Issue by leighman** [psalm/psalm-plugin-laravel#24]
vimeo/psalm: 3.9.3
psalm/plugin-laravel: 1.1.0
laravel/framework: 5.6.39

 `Illuminate\Support\Facades\Date` seems to have only been introduced in laravel 6

**Comment by pristinesource** [comment]
This is an issue in laravel-ide-helper.  I have opened an issue ticket there for it. 
https://github.com/barryvdh/laravel-ide-helper/issues/911

**Comment by mr-feek** [comment]
I noticed this also @pristinesource . I think we might want to ignore those exceptions...

**Comment by mr-feek** [comment]
This should be fixed now :)
