### ISSUE TITLE
ModelPropertyAccessorHandler::getClassLikeNames() returns unnecessary classes

### ISSUE THREAD

**Issue by zlodes** [psalm/psalm-plugin-laravel#244]
**Describe the bug**
Seems that `ModelPropertyAccessorHandler::getClassLikeNames()` returns a lot of non-model classes:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/1114387/209360298-917bdc84-154a-413f-b44d-3d9ace7c34a9.png">

It affects performance and may affect other classes property resolving.

**Impacted Versions**
2.0.2

**Additional context**

- PHP 8.2
- Psalm 5.4.0

**Comment by mr-feek** [comment]
You didn't include the version of ide-helper used in your report, but we currently rely on the ide helper models generator command to find the models in your application -- 

2 choices here: 

1) fix upstream in laravel-ide-helper
2) remove reliance on the ide-helper models command, and find the model classes ourselves by looping through the src directories being analyzed and checking the parent prototype of the inheritance chain to see if it is an eloquent model

**Comment by lptn** [comment]
I've reported an issue: https://github.com/barryvdh/laravel-ide-helper/issues/1414
