### ISSUE TITLE
Model stubs are not generated

### ISSUE THREAD

**Issue by dkuzmenchuk** [psalm/psalm-plugin-laravel#247]
**Describe the bug**
Both fake model commands ([FakeModelsCommand210.php](https://github.com/psalm/psalm-plugin-laravel/blob/master/src/Fakes/FakeModelsCommand210.php) and [FakeModelsCommand291.php](https://github.com/psalm/psalm-plugin-laravel/blob/master/src/Fakes/FakeModelsCommand291.php)) override method `getPropertiesFromTable` and contain the single call of `$this->getProperties($model)` in the method body.
The problem is that method `getProperties` does not exist anywhere in the current plugin or Psalm sources. As I see by the branch history, this method existed in the trait [FakeModelsCommandLogic.php](https://github.com/psalm/psalm-plugin-laravel/blob/master/src/Fakes/FakeModelsCommandLogic.php). But it was renamed to `getPropertiesFromTable` in the commit [0591299](https://github.com/psalm/psalm-plugin-laravel/commit/05912991852d967921a70bc69f3d4aafd888aace#diff-ae2fe16b0f8772abe2493429bdcd3a0a6cfba3d7b393d995028e9eb93c51597aR31).
As a result, the plugin cannot generate the stubs for the Eloquent models, file `models.stubphp` is empty. So Psalm report contains a lot of errors related to the Eloquent "magic".

Please let me know if you want me to create PR to rename the method `getPropertiesFromTable` back to `getProperties`.

**Impacted Versions**
```
barryvdh/laravel-ide-helper           v2.12.3
beyondcode/laravel-dump-server        1.8.0
bugsnag/bugsnag-laravel               v2.24.0
fruitcake/laravel-cors                v3.0.0
genealabs/laravel-model-caching       0.12.5
genealabs/laravel-pivot-events        9.0.4
jackwh/laravel-new-relic              v1.0.2
laravel/cashier                       v12.17.2
laravel/framework                     v9.29.0
laravel/serializable-closure          v1.2.2
laravel/socialite                     v5.5.5
laravel/tinker                        v2.7.2
orklah/psalm-insane-comparison        v2.2.0
psalm/plugin-laravel                  v2.0.2
psalm/plugin-phpunit                  0.18.4
spatie/laravel-newsletter             4.11.0
spatie/laravel-ray                    1.30.0
staudenmeir/laravel-cte               v1.6.2
vimeo/psalm                           5.x-dev 4e177bf
```

**Additional context**
PHP 8.1.9
Composer version 2.4.2

**Comment by mr-feek** [comment]
Hmm, I'm a bit confused about this one. It's admittedly been quite a long time since I looked into how this portion of the library works -- 

don't these "fake commands" override the logic of the base laravel ide helper command (which has the method definition for `getPropertiesFromTable`)? https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/ModelsCommand.php#L468

**Comment by dkuzmenchuk** [comment]
@mr-feek yes, you're right. As I see these "fake commands" override the logic of the command from laravel-ide-helper. "Fake commands" are using "fake filesystem" to generate model stubs without an active database connection.

But the problem is that "fake commands" contain the method `getPropertiesFromTable` which overrides methods from the laravel-ide-helper command. This method calls method `getProperties`. But this method exists neither in the current plugin sources nor laravel-ide-helper sources.
At the same time trait `FakeModelsCommandLogic` which is used in both fake commands also contains the method `getPropertiesFromTable`. Before the commit [0591299](https://github.com/psalm/psalm-plugin-laravel/commit/05912991852d967921a70bc69f3d4aafd888aace#diff-ae2fe16b0f8772abe2493429bdcd3a0a6cfba3d7b393d995028e9eb93c51597aR31) it has name `getProperties` and everything worked correctly as I guess. But in the commit [0591299](https://github.com/psalm/psalm-plugin-laravel/commit/05912991852d967921a70bc69f3d4aafd888aace#diff-ae2fe16b0f8772abe2493429bdcd3a0a6cfba3d7b393d995028e9eb93c51597aR31) method was renamed to `getPropertiesFromTable`. I'm not sure why this happened.

But if the class and trait have the same method, the class' method has a higher priority. So method from trait is not used anywhere in the current plugin. And as a result, model stubs are not generated at all.

I was a bit confused because this commit was merged about 9 months ago and I did not find that anyone faced this problem. 
But after a small investigation I found that if I rename trait's method to `getProperties` to make it callable from the "fake command", psalm stops reporting the errors regarding the unknown model's methods and properties. And the file `models.stubphp` contains stubs for all models in the project.

Please let me know if I'm somewhere wrong in my investigation.

**Comment by lptn** [comment]
@dkuzmenchuk 
thanks for your contribution. Feel free to close the issue (fixed by https://github.com/psalm/psalm-plugin-laravel/pull/248)
