### ISSUE TITLE
Getting UndefinedMagicMethod on query scopes

### ISSUE THREAD

**Issue by benjivm** [psalm/psalm-plugin-laravel#26]
Model scope:
```php
public function scopeAuthoredBy($query, User $user)
{
    return $query->whereHas('author', function ($subQuery) use ($user) {
        $subQuery->where('id', $user->id);
    });
}
```

Implementation:
```php
/**
 * @return \Illuminate\Http\JsonResponse
 */
public function recentlyAuthored()
{
    $reports = Report::with('categories', 'customer')
        ->authoredBy(Auth::user())
        ->latest()
        ->get()
        ->take(5);

    return response()->json(ReportResource::collection($reports));
}
```

Psalm's result:
```bash
ERROR: UndefinedMagicMethod - app\Http\Controllers\AdminDashboardController.php:18:15 - Magic method Illuminate\Database\Eloquent\Builder::authoredby does not exist
            ->authoredBy(Auth::user())
```

**Comment by karllhughes** [comment]
I'm running into the same issue. Any way to fix or work around it?

**Comment by chatii** [comment]
@karllhughes 
I had the same problem. In my project, I was able to avoid it by taking the following steps.

1. `php artisan ide-helper:models --write` to prepare annotations for the model.
2. Rewrite the scope annotation (`@method`)
    - before: `@method static \Illuminate\Database\Eloquent\Builder|\App\Models\MyModel byHogeId($hoge_id = null)`
    - after: `@method static byHogeId($hoge_id = null): \Illuminate\Database\Eloquent\Builder`
3. Executing `psalm`

**Comment by mr-feek** [comment]
I added a test case for this and wasn't able to reproduce the issue -- feel free to reopen if you think I missed something! https://github.com/psalm/psalm-plugin-laravel/commit/402ad732442051fd8ba4a7f1c56321a178c3d229

**Comment by tjmmm** [comment]
i have the same issue.

If `TModel` has scope methods, `Eloquent\Builder<TModel>` has the same.

```php
$users = User::query()->active()->get();
```

**Comment by HenkPoley** [comment]
Do you all happen to use the `--show-info=true` parameter?

It appears at the most strict level, the Laravel Eloquent methods still peek through. Without 'Show info' I don't see this INFO message.
