### ISSUE TITLE
Multiple suppress don't work

### ISSUE THREAD

**Issue by keizah7** [psalm/psalm-plugin-laravel#347]
Multiple suppress don't work

```bash
ERROR: UnusedClass - database/factories/AttributeGroupFactory.php:12:7 - Class Database\Factories\AttributeGroupFactory is never used (see https://psalm.dev/075)
class AttributeGroupFactory extends Factory
```

```php
<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @psalm-suppress UnusedClass, MissingTemplateParam
 */
class AttributeGroupFactory extends Factory
{
    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        $title = faker_translation('lastName');

        return [
            'title' => $title,
        ];
    }
}
```

**Comment by lptn** [comment]
Hey @keizah7 
This is psalm-related issue (not the plugin one), can you please report about it on https://github.com/vimeo/psalm repository?

**Comment by keizah7** [comment]
> Hey @keizah7 This is psalm-related issue (not the plugin one), can you please report about it on https://github.com/vimeo/psalm repository?

https://github.com/vimeo/psalm/issues/10144

**Comment by keizah7** [comment]
> Hey @keizah7 This is psalm-related issue (not the plugin one), can you please report about it on https://github.com/vimeo/psalm repository?

I think it's related to this package, because after installing core package, problem dissapears

**Comment by lptn** [comment]
@keizah7 

it's failed with this package/plugin because this package adds TemplateParam checks. But Psalm itself checks for suppressed issues, plugin does not do anything with `@psalm-suppress` annotations - it just delegates it to psalm.


The best you can do is to specify template type:
```php

<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @psalm-suppress UnusedClass, MissingTemplateParam
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\AttributeGroup> 
 */
class AttributeGroupFactory extends Factory
{
    /**
     * Define the model's default state.
     */
    public function definition(): array
    {
        $title = faker_translation('lastName');

        return [
            'title' => $title,
        ];
    }
}
```
