### ISSUE TITLE
`findOrFail` stub doesn't have `@throws`

### ISSUE THREAD

**Issue by yyueniao** [psalm/psalm-plugin-laravel#349]
**Describe the bug**
I note that `findOrFail` has a stub type:
```php
/**

     * @template T

     * @param  T $id

     * @param  list<non-empty-string>  $columns

     * @psalm-return (T is (array|\Illuminate\Contracts\Support\Arrayable) ? \Illuminate\Database\Eloquent\Collection<int, TModel> : TModel)

     */

    public function findOrFail($id, $columns = ['*']) {}
```
But `findOrFail` should throw `ModelNotFoundException`. Since I am using [checkForThrowsDocblock](https://psalm.dev/docs/running_psalm/configuration/#checkforthrowsdocblock) config so IMO I would like to enforce developers handle this exception.

**Impacted Versions**
Latest version

**Additional context**
Thanks for your effort of maintaining this amazing library.

**Comment by lptn** [comment]
done by 0c5545e
