### ISSUE TITLE
_ide_helper_models.php isn't loaded in github actions

### ISSUE THREAD

**Issue by brendt** [psalm/psalm-plugin-laravel#54]
I'm getting these kinds of errors when running psalm in a github action:

```
ERROR: UndefinedMagicPropertyFetch - app/Context/Balance/Projectors/BalanceProjector.php:35:9 - Magic instance property Illuminate\Database\Eloquent\Model::$amount is not defined (see https://psalm.dev/218)
        $balance->amount += $event->amount;
```

Running psalm locally doesn't yield these errors. I'm sure `_ide_helper_models.php` is available within the github action, since it's committed in the repository.

**Comment by mr-feek** [comment]
Hey @brendt, are you able to share the repo having issues? I'll gladly take a look! We don't yet run any model tests for this plugin, so I'm not sure off the top of my head.

**Comment by brendt** [comment]
Unfortunately I cannot share the repo, since it's a client project. I'll try to setup a dummy repository to share though!

**Comment by brendt** [comment]
Making a test project, I realised the ide helper files were outdated in our real project, which was the cause of the issue. Sorry for the overhead!
