### ISSUE TITLE
Run tests on actual laravel project

### ISSUE THREAD

**Issue by mr-feek** [psalm/psalm-plugin-laravel#66]
**Is your feature request related to a problem? Please describe.**
Let's clone our supported laravel releases during our CI pipeline and run this plugin and an accompanying baseline file on them. That will help to ensure that we don't have any regressions.

**Describe the solution you'd like**
Larastan and psalm itself both do something similar --  let's use them for inspiration

**Comment by muglug** [comment]
Have a look at Psalm’s test-with-real-projects.sh for inspiration

**Comment by mr-feek** [comment]
https://github.com/psalm/psalm-plugin-laravel/pull/87
