### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by vladyslavstartsev** [psalm/psalm-plugin-laravel#90]
**Describe the bug**
When using `psalm` with Laravel plugin I have, as I think, memory leak.
At least, when I run it with plugin, I have 
```text
psalm --no-cache
Scanning files...
PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 20480 bytes) in /var/www/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 300
PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 65536 bytes) in /var/www/vendor/sentry/sentry/src/Integration/FrameContextifierIntegration.php on line 56
```

when I run without plugin, it works fine

**Impacted Versions**
laravel/framework 5.8
vimeo/psalm 3.9
psalm/plugin-laravel 1.2.1
Can't give more info due to NDA.

**Additional context**
I can provide some other info (logs all dependencies) but only in private DM

**Comment by muglug** [comment]
Hey, please try to narrow it down a bit more - run with `--debug` to figure out what file it’s coming from, and see if running on just that file still produces the leak

**Comment by vladyslavstartsev** [comment]
:facepalm: my bad, I've made cyclic dependency, that's why it was not working
